language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    env: OCAML_VERSION=4.07 OPAM_VERSION=2.0
  - os: linux
    env: OCAML_VERSION=4.07 OPAM_VERSION=2.0
  - os: linux
    env: OCAML_VERSION=4.06 OPAM_VERSION=2.0
  - os: linux
    env: OCAML_VERSION=4.05 OPAM_VERSION=2.0
  - os: linux
    env: OCAML_VERSION=4.04 OPAM_VERSION=2.0
  - os: linux
    env: OCAML_VERSION=4.03 OPAM_VERSION=2.0
