language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libhdf5-dev
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02
