language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.06
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.04
  - os: linux
    env: OCAML_VERSION=4.03
  - os: linux
    env: OCAML_VERSION=4.02
